apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: akashray3/docker_jenkins_build:latest # Replace with the actual image tag
          ports:
            - containerPort: 30620 # Replace with the port your Tetris game listens on
